sudo: required
services:
  - docker

before_install:
  - docker build -t lejarokos/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lejarokos/docker-react npm run test -- --coverage --watchAll=false